service: phanalytics

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - dist/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  environment:
    AWS_PROFILE: floom

functions:
  players:
    handler: src/index.main
    events:
      - http:
          path: players
          method: get
