export const SET_PLAYERS = 'SET_PLAYERS';
export const SET_PLAYERS_LOAD_STATE = 'SET_PLAYERS_LOAD_STATE';
export const SET_QUALIFYING_OFFER = 'SET_QUALIFYING_OFFER';
export const SET_CUTOFF_SALARY = 'SET_CUTOFF_SALARY';
